### ISSUE TITLE
HTTP server

### ISSUE THREAD

**Issue by larien** [larien/learn-go-with-tests#23]

**Comment by fsmiamoto** [comment]
@ehriq  @larien 
Essa seção está sendo traduzida atualmente?
Se não estiver, posso começar a tradução!

**Comment by larien** [comment]
Vi que o @ehriq tem feito algumas atualizações [aqui](https://github.com/larien/learn-go-with-tests/tree/traducao/http-server). Como as coisas estão indo, moço?

**Comment by ehriq** [comment]
Eu estou tentando dedicar algumas horas por semana, mas está um pouco complicado. Está andando a passos lentos. Se o @fsmiamoto quiser dar continuidade, sem problemas.

**Comment by lucasdittrichzup** [comment]
@larien e @ehriq eu vi que esse tópico foi traduzido por completo, mas não está disponível [aqui](https://larien.gitbook.io/aprenda-go-com-testes/criando-uma-aplicacao/http-server).

O que falta para ir ao ar?

**Comment by larien** [comment]
Falta revisão, que está disponível [aqui](https://github.com/larien/learn-go-with-tests/pull/91) :) não tenho tido tempo para investir no repo, mas fique à vontade caso queira ajudar :D duas aprovações são necessárias para o capítulo ir para a branch principal
