### ISSUE TITLE
JSON, routing and embedding

### ISSUE THREAD

**Issue by larien** [larien/learn-go-with-tests#24]

**Comment by Ronald-TR** [comment]
Oi, gostaria de traduzir este trecho :D

**Comment by larien** [comment]
OI, Ronald :D te coloquei como colaborador, só aceitar por lá e começar :) obrigada pela ajuda <3

**Comment by Ronald-TR** [comment]
Duvida: Também é para traduzir os códigos?

**Comment by larien** [comment]
Sim. Se possível as variáveis, constantes, nomes de métodos e tudo o que não for keyword hehehe

**Comment by Ronald-TR** [comment]
auhauhauha poxa, algumas coisas vão ficar muito feias e fugir de convenções. Como `NewPlayerServer`=`NovoJogadorServidor`, `router`=`roteador`, `store`=`loja`

Fica muito estranho xD

**Comment by larien** [comment]
`NewPlayerServer` pode ficar `NovoServidorDoJogador`, `roteador` é um termo comum do nosso cotidiano e `store` no nosso contexto fica melhor como `armazenamento`  ou algo do tipo xDD
A gente teve esse debate em um ponto anterior da tradução e, como queremos facilitar o entendimento para quem fala a língua portuguesa, é melhor evitar usar os termos em inglês. Não precisa ser tradução literal, mas uma tradução que passe a ideia do que a versão original quer dizer
Não vai ser em um livro traduzido que as pessoas vão querer aprender inglês, é uma boa não criar mais uma barreira pra ela :P

**Comment by Ronald-TR** [comment]
Eentendi, bacana!
Um glossário com exemplos de transcrições para o português seria bom nesse sentido. Tanto para os novos tradutores deste ou de futuros ebooks que seguirem esta filosofia.

Valeu pela explicação!

**Comment by larien** [comment]
É uma ótima ideia, jovem
Vou criar uma issue sobre isso para fazer quando vir a calhar :D

**Comment by larien** [comment]
Hey, jovem @Ronald-TR, tudo bem?
Agora que estou de férias estou dando uma geral para finalizar essa primeira tradução do livro

Ainda tem interesse em continuar a tradução? Posso pegar a partir da parte que tu parou :)

**Comment by Ronald-TR** [comment]
Oi Lauren! Desculpa o sumiço, eu pretendo sim! Mas antes preciso reorganizar minha rotina hahaha
Se eu não entregar nada até o fim deste mês (01/2020) sinta-se livre para abrir o branch para novos colaboradores, aliás feliz ano novo e parabéns pelo ótimo trabalho! E me desculpa pelo entrave.

Abraços!

**Comment by larien** [comment]
Que nada, moço, vou manter com você e pegar a tradução quando terminar as duas PRs que estão abertas. Não tem pressa não, não sei quando consigo terminar essas revisões ainda hahaha feliz ano novo e obrigada pela ajuda <3
