### ISSUE TITLE
IO and sorting

### ISSUE THREAD

**Issue by larien** [larien/learn-go-with-tests#25]

**Comment by wps13** [comment]
Olá, gostaria de colaborar.

**Comment by larien** [comment]
Te coloquei como colaboradora, só aceitar no e-mail e começar :) muito obrigada 💙💙

**Comment by wps13** [comment]
@larien obrigada ^^

**Comment by wps13** [comment]
@larien É necessário traduzir as 9 versões dos códigos?

**Comment by larien** [comment]
@wps13 Desculpa a demora </3 vi que tu seguiu certo e traduziu os códigos. Sim, é isso mesmo :)
