### ISSUE TITLE
WebSockets

### ISSUE THREAD

**Issue by larien** [larien/learn-go-with-tests#28]

**Comment by larien** [comment]
@giovana-morais posso te colocar nesse?

**Comment by giovana-morais** [comment]
vamo que vamo pq agora eu quero ver este livro terminadíssimo

**Comment by larien** [comment]
Hey, moça @giovana-morais, tudo bem?
Agora que estou de férias estou dando uma geral para finalizar essa primeira tradução do livro

Ainda tem interesse em continuar a tradução? Quer ajuda com alguma parte? :D
