### ISSUE TITLE
Instalação do Go com distribuição Linux

### ISSUE THREAD

**Issue by larien** [larien/learn-go-with-tests#41]
Edit.: Esse tópico não existe na documentação oficial. É uma adição ao conteúdo original.

**Comment by milhomem** [comment]
Aonde está essa seção? Não consegui achar.

**Comment by larien** [comment]
Ela não existe na documentação oficial. Essa issue é uma adição ao conteúdo original :)

**Comment by ramonsilvanet** [comment]
Olá pessoal, eu quero ajudar,  e criei uma seção de "Instalação no Linux", e agora que abrir um PR, mas estou sem permissão.

**Comment by larien** [comment]
Hey, moço, obrigada pela ajuda!
Te adicionei como colaborador. Pode ver se consegue submeter o PR?

**Comment by ramonsilvanet** [comment]
Obrigado Lauren
