### ISSUE TITLE
2. Hello, world

### ISSUE THREAD

**Issue by larien** [larien/learn-go-with-tests#9]

**Comment by diegonvs** [comment]
Eu continuo sem poder dar assign para mim 😭

Posso pegar esse tópico?

**Comment by Dimenicius** [comment]
Olá, essa issue ta disponível? estou procurando algo pra contribuir nessa hacktober

**Comment by larien** [comment]
Hey! Infelizmente não, a issue está sob responsabilidade do @diegonvs :< as issues de tradução já foram selecionadas, mas cê pode ajudar revisando algum texto já publicado ou pegando as issues de criação de conteúdo :)

**Comment by larien** [comment]
@Dimenicius tem uma issue comigo falando sobre Select, quer ela pra ti? #19

**Comment by Dimenicius** [comment]
Opa! aceito ficar com ela sim!

**Comment by larien** [comment]
closed by #75
